### ISSUE TITLE
Shaders on linux

### ISSUE THREAD

**Issue by ewgenius** [neokabuto/OpenTKTutorialContent#1]
Hello! I'm trying to reproduce simple vbo example with shaders. I cloned your repo - first tutorial runs ok, drawing colored triangle, but others shows only blue screen
![2015-03-01 23 09 02](https://cloud.githubusercontent.com/assets/827338/6432610/37d56a74-c068-11e4-8047-25c572357478.png)

Is there any issues with running opentk shaders on linux?
I'm on ubuntu 14.04, with mono 3.12.0 and latest monodevelop, video - intel hd 4000.

**Comment by neokabuto** [comment]
I haven't tried it on Linux yet (IIRC I've had some blog comments about it working with some modifications), but I can at least confirm that it works on the HD 4000 on Windows.

Did you need to modify the tutorial projects to run them with Mono? I'll set up Ubuntu to see if I can reproduce this.

**Comment by ewgenius** [comment]
All is working without any errors, but it seems like any example, rendered with shaders is not displaing. I can't find any issue with it on linux, so may be it is problem with drivers or something else on my local system.

**Comment by BartoszJasinski** [comment]
I have the same problem on Devuan using Mono 5.18. And these are terminal outputs:
```
 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

error: linking with uncompiled shadererror: linking with uncompiled shader
```
Tutorial1 works properly.

**Comment by neokabuto** [comment]
@BartoszJasinski Can you tell me what graphics card and drivers you have?

**Comment by simonthalen** [comment]
Oh this is the same as my problem. Sorry for the double post then!

**Comment by neokabuto** [comment]
Finally got a chance to check this. What I found is that switching the version in the shaders to `130` instead of `330` works for tutorials 4-7, but beyond that it would require rewriting the functions added in more recent OpenGL versions (e.g. [inverting a matrix](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/inverse.xhtml)). I'm looking into if there's a way to get them all working.

**Comment by neokabuto** [comment]
As an update, I was able to get all the tutorials running (to some, very buggy extent, not really worth doing) by setting the `MESA_GL_VERSION_OVERRIDE` environment variable to `3.2` to force it to run as OpenGL 3.2, with the versions in the shaders set to `140`. I'm still looking into what might be an actual fix, looks like the context it's creating on non-Windows platforms isn't the newest version automatically.
