### ISSUE TITLE
You cannot use StringBuilder in GetActiveAttrib . This is for OpenTk3

### ISSUE THREAD

**Issue by uzername** [neokabuto/OpenTKTutorialContent#10]
https://github.com/neokabuto/OpenTKTutorialContent/blob/60e9668c2f283a3d9600d62fd67a30e619e7d9c9/OpenTKTutorial6/OpenTKTutorial6/ShaderProgram.cs#L79

**Comment by neokabuto** [comment]
I'm currently waiting for OpenTK 4 to release (see https://github.com/opentk/opentk/issues/823) before updating the tutorials to a newer version. This is useful to have as a note, but we'll have to see how the API is set up in when the new version releases.

**Comment by Perksey** [comment]
Alternatively you could use my new binding to OpenGL: https://github.com/Ultz/Silk.NEt

**Comment by neokabuto** [comment]
Hmm, that looks promising. That would really be a separate project (since I don't want to destroy the OpenTK content and it'd be about the same as starting over). Looks like your project is in need of more tutorials and examples, though, I'll have to play around with it.
