### ISSUE TITLE
Matrix.Scale was changed to Matrix.CreateScale in OpenTK 3

### ISSUE THREAD

**Issue by uzername** [neokabuto/OpenTKTutorialContent#12]
https://github.com/neokabuto/OpenTKTutorialContent/blob/60e9668c2f283a3d9600d62fd67a30e619e7d9c9/OpenTKTutorial7/OpenTKTutorial7/Cube.cs#L80

**Comment by neokabuto** [comment]
Same thing as in #10, thank you very much for making a note of these, but I'm waiting for the next major version since it's already coming.

**Comment by neokabuto** [comment]
On second thought, I'm going to put together the OpenTK 3 changes in their own branch (see #13) since I realized it's a lot less code than I thought. These changes will be included over there.
