### ISSUE TITLE
Missing files in repo

### ISSUE THREAD

**Issue by johnnyontheweb** [neokabuto/OpenTKTutorialContent#2]
teapot.obj and cow.obj are missing in the repo. they are needed for the tutorial7

**Comment by neokabuto** [comment]
They're available from https://groups.csail.mit.edu/graphics/classes/6.837/F03/models/

IIRC, I didn't include them in the repo because I wasn't sure on copyright and they're not reused in later tutorials (because they aren't texture mapped).

**Comment by Timmitry** [comment]
Additionally, the following files are missing for Tutorial 8-2. Where can I find these? I only  found earth.obj in the Blog page for Tutorial 8-2.

cubedie.obj
earth.obj
sphere.obj

**Comment by neokabuto** [comment]
@Timmitry Sorry about that, .obj files were excluded by the default .gitignore file. Those three should be included now.
